on: [pull_request]
name: Check markdown links
jobs:
  linkChecker:
    runs-on: jp-lab
    steps:
      - name: Hey yoh!
        run: echo 'Hi!'
      - name: Checkout
        uses: actions/checkout@v1
        with:
          persist-credentials: 'false'
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Example of message !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
