on: [pull_request]
name: Check markdown links
jobs:
  linkChecker:
    runs-on: jp-lab
    steps:
      - uses: actions/checkout@v2
        run: pwd && ls -l
      - name: Link Checker
        with:
          args: -v "**/*.md"
        uses: lycheeverse/lychee-action@v1.0.4
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./lychee/out.md
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
