on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Check markdown links
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        with:
          args: -v "**/*.md"
        uses: lycheeverse/lychee-action@v1.0.4
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
